// Correct Mic2 readings for comparability
// Generated by ChatGPT on 09.09.2026

/* Raw Data

    frequency_Hz,mic1_rms,mic2_rms,mic2_mic1_ratio
    100,12.597,6.761,0.5367
    Testing 440 Hz. Confirm! y
    440,99.074,56.042,0.5657
    Testing 1000 Hz. Confirm! y
    1000,128.187,56.668,0.4421
    Testing 4000 Hz. Confirm! y
    4000,304.552,58.345,0.1916
    Testing 10000 Hz. Confirm! y
    10000,43.295,11.125,0.2570

    frequency_Hz,mic1_rms,mic2_rms,mic2_mic1_ratio
    Testing 100 Hz. Confirm! y
    100,13.108,6.379,0.4867
    Testing 200 Hz. Confirm! y
    200,35.311,13.790,0.3905
    Testing 440 Hz. Confirm! y
    440,125.779,64.501,0.5128
    Testing 600 Hz. Confirm! y
    600,174.522,64.788,0.3712
    Testing 1000 Hz. Confirm! y
    1000,191.161,64.389,0.3368
    Testing 2000 Hz. Confirm! y
    2000,357.754,60.620,0.1694
    Testing 4000 Hz. Confirm! y
    4000,247.301,64.873,0.2623
    Testing 6000 Hz. Confirm! y
    6000,149.953,60.968,0.4066
    Testing 8000 Hz. Confirm! y
    8000,203.493,65.799,0.3233
    Testing 10000 Hz. Confirm! y
    10000,47.053,60.597,1.2878 :chenged to: 10000,43.295,11.125,0.2570


*/

#include <cmath>
#include"Structures.h"

// ------------------------------------------------------------
// Calibration data
//
// Mic 1 is the reference.
//
// Values are the correction required to make Mic 2
// equivalent to Mic 1.
//
// correction_dB = 20 * log10(Mic1 / Mic2)
// ------------------------------------------------------------

const float calibrationFreq[] = {
    100.0,
    200.0,
    440.0,
    600.0,
    1000.0,
    2000.0,
    4000.0,
    6000.0,
    8000.0,
    10000.0
};

const float calibrationDB[] = {
    6.254773075129871,
    8.167579235733616,
    5.80103966978478,
    8.607840649063512,
    9.452558343447762,
    15.421731880106236,
    11.624034188192926,
    7.816652513959603,
    9.80788590776888,
    11.80133753337411
};

const int CAL_POINTS = 10;


// ------------------------------------------------------------
// Calculate correction in dB
//
// Uses logarithmic interpolation in frequency.
// This is more appropriate for audio than linear
// interpolation in Hz.
// ------------------------------------------------------------

float getCalibrationDB(float frequency) {

    // Mic 1 is our reference
    // so it needs no correction.
    
    if (frequency <= calibrationFreq[0]) {
        return calibrationDB[0];
    }

    if (frequency >= calibrationFreq[CAL_POINTS - 1]) {
        return calibrationDB[CAL_POINTS - 1];
    }

    // Find surrounding calibration points
    for (int i = 0; i < CAL_POINTS - 1; i++) {

        if (frequency >= calibrationFreq[i] &&
            frequency <= calibrationFreq[i + 1]) {

            float f1 = calibrationFreq[i];
            float f2 = calibrationFreq[i + 1];

            float dB1 = calibrationDB[i];
            float dB2 = calibrationDB[i + 1];

            // Logarithmic frequency interpolation
            float x =
                (log10(frequency) - log10(f1)) /
                (log10(f2) - log10(f1));

            return dB1 + x * (dB2 - dB1);
        }
    }

    return 0.0;
}


// ------------------------------------------------------------
// Correct one FFT frequency/magnitude pair
// ------------------------------------------------------------

FrequencyMagnitude correctFreqMag(
    FrequencyMagnitude input,
    Microphone microphone
) {

    FrequencyMagnitude output = input;

    // Mic 1 is the reference
    if (microphone == MIC1) {
        return output;
    }

    // Get frequency-dependent correction
    float correctionDB =
        getCalibrationDB(input.frequency);

    // Convert dB correction to linear magnitude
    float correction =
        pow(10.0, correctionDB / 20.0);

    // Apply correction
    output.magnitude =
        input.magnitude * correction;

    return output;
}

void correctFreqMag(FrequencyMagnitude input [], int bands, Microphone microphone){
    for (int b = 0; b < bands; ++b){
        input[b] = correctFreqMag(input[b], microphone);
    }
}